# Generated by Django 4.1.4 on 2023-10-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='board_ten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_ten', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='board_twelve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_twelve', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
            ],
        ),
    ]
