# Generated by Django 4.1.4 on 2023-11-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_board_ten_board_twelve_university'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='year',
            new_name='years',
        ),
    ]
