# Generated by Django 4.1.4 on 2023-11-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='branch',
        ),
    ]
