# Generated by Django 4.1.4 on 2023-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=models.CharField(default=233, max_length=255),
            preserve_default=False,
        ),
    ]
