# Generated by Django 4.1.4 on 2023-10-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
