# Generated by Django 4.1.4 on 2023-10-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_course_profile_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accept', 'accept'), ('reject', 'reject')], max_length=255),
        ),
    ]
