# Generated by Django 4.1.4 on 2023-10-07 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_alter_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='board_ten',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='board_twelve',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='percentage_ten',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='percentage_twelve',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s_end',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='s_start',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ten_result',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twelve_result',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
        migrations.CreateModel(
            name='educational_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_ten', models.CharField(blank=True, max_length=255)),
                ('percentage_ten', models.CharField(blank=True, max_length=255)),
                ('ten_result', models.FileField(blank=True, upload_to='')),
                ('board_twelve', models.CharField(blank=True, max_length=255)),
                ('percentage_twelve', models.CharField(blank=True, max_length=255)),
                ('twelve_result', models.FileField(blank=True, upload_to='')),
                ('university', models.CharField(blank=True, max_length=255)),
                ('cgpa', models.CharField(blank=True, max_length=255)),
                ('s_start', models.CharField(blank=True, max_length=255)),
                ('s_end', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
