# Generated by Django 4.1.4 on 2023-10-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_board_ten_remove_profile_board_twelve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student')], max_length=255),
        ),
    ]
