# Generated by Django 4.1.4 on 2023-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational_details',
            name='verify',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=255),
        ),
    ]
