# Generated by Django 4.1.4 on 2023-10-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.CharField(choices=[('admin', 'admin'), ('student', 'student')], max_length=255),
        ),
    ]
