# Generated by Django 4.1.4 on 2023-10-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admission',
            field=models.CharField(default='True', max_length=255),
        ),
    ]
