# Generated by Django 4.1.4 on 2023-10-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_profile_is_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_admission',
        ),
    ]
