# Generated by Django 4.1.4 on 2023-11-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_profile_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
    ]
