# Generated by Django 4.1.4 on 2023-11-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_profile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational_details',
            name='is_submit',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educational_details',
            name='verify',
            field=models.CharField(choices=[('pending', 'pending'), ('accept', 'accept'), ('reject', 'reject')], default='false', max_length=255),
        ),
    ]
