# Generated by Django 4.1.4 on 2023-11-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_educational_details_is_submit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(blank=True, default=2, max_length=255),
            preserve_default=False,
        ),
    ]
