# Generated by Django 4.1.4 on 2023-11-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educational_details',
            name='is_submit',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=255),
        ),
    ]
