# Generated by Django 4.1.4 on 2023-11-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_educational_details_is_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educational_details',
            name='is_submit',
        ),
    ]
